import Terminal from "./Terminal.js";
const terminal = new Terminal();
terminal.theme = "dark";
terminal.start();
const json = `[{"name":{"common":"Uganda","official":"Republic of Uganda","nativeName":{"eng":{"official":"Republic of Uganda","common":"Uganda"},"swa":{"official":"Republic of Uganda","common":"Uganda"}}},"tld":[".ug"],"cca2":"UG","ccn3":"800","cca3":"UGA","cioc":"UGA","independent":true,"status":"officially-assigned","unMember":true,"currencies":{"UGX":{"name":"Ugandan shilling","symbol":"Sh"}},"idd":{"root":"+2","suffixes":["56"]},"capital":["Kampala"],"altSpellings":["UG","Republic of Uganda","Jamhuri ya Uganda"],"region":"Africa","subregion":"Eastern Africa","languages":{"eng":"English","swa":"Swahili"},"translations":{"ara":{"official":"جمهورية أوغندا","common":"أوغندا"},"ces":{"official":"Ugandská republika","common":"Uganda"},"cym":{"official":"Republic of Uganda","common":"Uganda"},"deu":{"official":"Republik Uganda","common":"Uganda"},"est":{"official":"Uganda Vabariik","common":"Uganda"},"fin":{"official":"Ugandan tasavalta","common":"Uganda"},"fra":{"official":"République de l'Ouganda","common":"Ouganda"},"hrv":{"official":"Republika Uganda","common":"Uganda"},"hun":{"official":"Ugandai Köztársaság","common":"Uganda"},"ita":{"official":"Repubblica di Uganda","common":"Uganda"},"jpn":{"official":"ウガンダ共和国","common":"ウガンダ"},"kor":{"official":"우간다 공화국","common":"우간다"},"nld":{"official":"Republiek Uganda","common":"Oeganda"},"per":{"official":"جمهوری اوگاندا","common":"اوگاندا"},"pol":{"official":"Republika Ugandy","common":"Uganda"},"por":{"official":"República do Uganda","common":"Uganda"},"rus":{"official":"Республика Уганда","common":"Уганда"},"slk":{"official":"Ugandská republika","common":"Uganda"},"spa":{"official":"República de Uganda","common":"Uganda"},"swe":{"official":"Republiken Uganda","common":"Uganda"},"urd":{"official":"جمہوریہ یوگنڈا","common":"یوگنڈا"},"zho":{"official":"乌干达共和国","common":"乌干达"}},"latlng":[1.0,32.0],"landlocked":true,"borders":["COD","KEN","RWA","SSD","TZA"],"area":241550.0,"demonyms":{"eng":{"f":"Ugandan","m":"Ugandan"},"fra":{"f":"Ougandaise","m":"Ougandais"}},"flag":"\uD83C\uDDFA\uD83C\uDDEC","maps":{"googleMaps":"https://goo.gl/maps/Y7812hFiGa8LD9N68","openStreetMaps":"https://www.openstreetmap.org/relation/192796"},"population":45741000,"gini":{"2016":42.8},"fifa":"UGA","car":{"signs":["EAU"],"side":"left"},"timezones":["UTC+03:00"],"continents":["Africa"],"flags":{"png":"https://flagcdn.com/w320/ug.png","svg":"https://flagcdn.com/ug.svg"},"coatOfArms":{"png":"https://mainfacts.com/media/images/coats_of_arms/ug.png","svg":"https://mainfacts.com/media/images/coats_of_arms/ug.svg"},"startOfWeek":"monday","capitalInfo":{"latlng":[0.32,32.55]}}]`;
terminal.displayTitle = true;
let humanized = terminal.json.humanize(json);
let minimized = terminal.json.minimize(humanized);
terminal.writeJSON(minimized);
